feat!: Update logic for SuperTokens.init and accepted parameters
supertokens/supertokens-android pull request #12
Opened 2022-05-11 06:05 UTC by nkshah2

WIP

2022-05-11 13:47 UTC, rishabhpoddar requested changes

2022-05-11 13:47 UTC, rishabhpoddar commented on Example/app/src/test/java/com/example/example/android/ConfigTests.java
> +/*
Why is this in android folder

2022-05-11 13:47 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/SuperTokens.java
> +            @Nullable String cookieDomain
Do we need `autoAddCredentials`?

2022-05-11 13:47 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/Utils.java
> +        public static String normaliseSessionScopeOrThrowError(String sessionScope) throws MalformedURLException {
Remove this func

2022-05-11 13:47 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/Utils.java
> +        static String sessionScopeHelper(String sessionScope) throws MalformedURLException {
Remove this func

2022-05-11 13:47 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/Utils.java
> +        }
remove this too

2022-05-11 13:47 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/Utils.java
> +            }
Not required

2022-05-11 13:47 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/Utils.java
> +        String cookieDomain;
Not required to have cookieDomain

2022-05-11 16:51 UTC, rishabhpoddar requested changes

2022-05-11 16:51 UTC, rishabhpoddar commented on app/src/main/java/io/supertokens/session/Utils.java
> +//        }
Remove this comment

2022-05-12 04:42 UTC, nkshah2 commented on app/src/main/java/io/supertokens/session/Utils.java
>                  String apiBasePath,
`NormalisedInputType` in supertokens-website has them stored as strings

2022-05-12 05:28 UTC, rishabhpoddar approved these changes

2022-05-12 05:30 UTC, merged