fix: session refresh loop in all request interceptors
supertokens/supertokens-android pull request #71
Opened 2024-06-06 13:29 UTC by anku255

## Summary of change

This PR fixes the session refresh loop in all the request interceptors that occurred when an API returned a 401 response despite a valid session. Interceptors now attempt to refresh the session a maximum of ten times before throwing an error. The retry limit is configurable via the `maxRetryAttemptsForSessionRefresh` option.

## Related issues
- Link to issue1 here
- Link to issue1 here

## Test Plan
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
   - Along with the associated array in `app/src/main/java/com/supertokens/session/Version.java`
- [ ] Changes to the version if needed
   - In `app/build.gradle`
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2024-06-06 22:16 UTC, porcellus approved these changes

2024-06-09 06:02 UTC, rishabhpoddar requested changes

2024-06-09 06:02 UTC, rishabhpoddar commented on CHANGELOG.md
> +
add migration guide (in this and all other sdks) since the position of the args have shifted in the init function

2024-06-10 05:54 UTC, rishabhpoddar approved these changes

2024-06-10 06:38 UTC, merged